#!/usr/bin/env/python

# Graphics color specifications:
GROUND_EDGE_COLOR_R = 1.0
GROUND_EDGE_COLOR_G = 1.0
GROUND_EDGE_COLOR_B = 1.0

GROUND_FACE_COLOR_R = 0.5
GROUND_FACE_COLOR_G = 0.5
GROUND_FACE_COLOR_B = 0.5

# LIGHT GREY:
LINK_COLOR_R = 0.75
LINK_COLOR_G = 0.75
LINK_COLOR_B = 0.75

# DARK GREY:
JOINT_COLOR_R = 0.2
JOINT_COLOR_G = 0.2
JOINT_COLOR_B = 0.2

# RED:
ENDEFF_COLOR_R = 1.0
ENDEFF_COLOR_B = 0.0
ENDEFF_COLOR_G = 0.0

# BLUE:
LINK_COM_COLOR_R = 0.0
LINK_COM_COLOR_B = 1.0
LINK_COM_COLOR_G = 0.0

# MAGENTA:
LINVEL_COLOR_R = 1.0
LINVEL_COLOR_G = 0.0
LINVEL_COLOR_B = 1.0

# CYAN:
ANGVEL_COLOR_R = 0.0
ANGVEL_COLOR_G = 1.0
ANGVEL_COLOR_B = 1.0

# YELLOW:
LINACC_COLOR_R = 1.0
LINACC_COLOR_G = 1.0
LINACC_COLOR_B = 0.0

# ORANGE:
ANGACC_COLOR_R = 1.0
ANGACC_COLOR_G = 0.6
ANGACC_COLOR_B = 0.0

# Graphics size specifications:
LINK_CYLINDER_RAD = 0.05
JOINT_CYLINDER_RAD = 0.055
JOINT_CYLINDER_LEN = 0.15

ENDEFF_SPHERE_RAD = 0.05

LINK_COM_SPHERE_RAD = 0.025

# Graphics cylinder parameters:
CYLINDER_SLICES = 10
CYLINDER_STACKS = 10

# Graphics disk parameters:
DISK_SLICES = 10
DISK_STACKS = 10

# Graphics sphere parameters:
SPHERE_SLICES = 10
SPHERE_STACKS = 10

# Graphics vector parameters:
VEC_RAD = 0.01
VEC_HEAD_RATIO = 0.1

# Graphics axes parameters:
AXES_LEN = 0.3

# Vector graphics scaling:
LINVEL_VEC_SCALE = 1.0
ANGVEL_VEC_SCALE = 1.0
LINACC_VEC_SCALE = 1.0
ANGACC_VEC_SCALE = 1.0

# Robot graphics alpha value:
ROBOT_ALPHA = 0.5
